name: Deploy deploy-app
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.QSB_HOST }}
          username: ${{ secrets.QSB_USER }}
          password: ${{ secrets.QSB_PWD }}
          script_stop: true
          script: |
            cd /opt/1panel/apps/openresty/openresty/www/sites/qsb3008.xyz/index
            ls -al
            rm -rf vue-proj
            git clone git@github.com:qsb3008/vue-proj.git -b ${{ github.ref_name }}
            cd vue-proj
            npm install
            npm run build
